@HostAddress = http://localhost:5225
@Version = v1

### Get all skills
GET {{HostAddress}}/api/{{Version}}/getskills
Accept: application/json

###

### Create a new Skill
POST {{HostAddress}}/api/{{Version}}/createskill
Content-Type: application/json
Accept: application/json

{
  "name": "VueJs",
  "description": "Ability to write vue js applications"
}
